### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by mfazrinizar** [widhisec/temp-mails#1]
Wid, dah bener-bener hilang ditelan bumi? Kalo belum, share kontak lu Wid.

**Comment by widhisec** [comment]
hp lagi rusak gan

**Comment by widhisec** [comment]
> Wid, dah bener-bener hilang ditelan bumi? Kalo belum, share kontak lu Wid.

hp lagi rusak gan

**Comment by mfazrinizar** [comment]
Oalah iya, sip.
